# Generated by Django 6.0 on 2026-01-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100, unique=True, verbose_name="Заголовок")),
                ("content", models.TextField(blank=True, null=True, verbose_name="Содержание")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, help_text="Загрузите фото", null=True, upload_to="blog/photos", verbose_name="Фото"
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True, help_text="Укажите кол-во просмотров", null=True, verbose_name="Дата создания"
                    ),
                ),
                ("published", models.BooleanField(blank=True, null=True)),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0, help_text="Укажите кол-во просмотров", verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
            },
        ),
    ]
