# Generated by Django 6.0 on 2025-12-27 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Название товара", max_length=100, verbose_name="Наименование")),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Название товара", max_length=100, verbose_name="Наименование")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="catalog/photo", verbose_name="Изображение"),
                ),
                ("price", models.IntegerField(blank=True, null=True, verbose_name="Цена за покупку")),
                ("created_at", models.DateField(blank=True, null=True, verbose_name="Дата создания")),
                ("updated_at", models.DateField(blank=True, null=True, verbose_name="Дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="catalog",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
