# Generated by Django 6.0 on 2026-02-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="published",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Опубликовано"),
        ),
    ]
