# Generated by Django 6.0 on 2026-02-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0, help_text="Укажите кол-во просмотров", verbose_name="Счетчик просмотров"
            ),
        ),
    ]
